name: harmonoid
description: A beautiful app to play all your music.
publish_to: 'none'
version: 0.1.0+5003

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  provider: ^5.0.0
  flutter_acrylic: ^0.0.2
  ffi: ^1.1.2
  libwinmedia:
    path: ./external/libwinmedia.dart
  flutter_media_metadata:
    git:
      url: https://github.com/alexmercerind/flutter_media_metadata.git
      ref: f7773003d97d6310f6aebf2d76bd6a19a65e6955
  fluentui_system_icons: ^1.1.136
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  filepicker_windows: ^2.0.0
  bitsdojo_window: ^0.1.1+1
  flutter_local_notifications: ^5.0.0
  file_picker: ^3.0.0
  permission_handler: ^6.1.1
  share: ^2.0.1
  palette_generator: ^0.3.0
  http: ^0.13.0
  path: ^1.8.0
  url_launcher: ^6.0.3
  implicitly_animated_reorderable_list: ^0.4.0-dev+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/about-header.jpg
    - assets/images/collection-album.jpg
    - assets/images/credits-albums.jpg
    - assets/images/credits-tracks.jpg
    - assets/images/credits-artists.jpg
    - assets/images/credits-exception.jpg
    - assets/images/discover-albums.jpg
    - assets/images/discover-tracks.jpg
    - assets/images/discover-artists.jpg
    - assets/images/exception.jpg
    - assets/images/credits-album-art-0.jpg
    - assets/images/credits-album-art-1.jpg
    - assets/images/credits-album-art-2.jpg
    - assets/images/credits-album-art-3.jpg
