name: harmonoid
description: Plays & manages your music library. Looks beautiful & juicy.
publish_to: "none"
version: 0.3.9+5018

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_layouts:
    path: external/adaptive_layouts
  animations: ^2.0.0
  audio_service: ^0.18.7
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  crypto: ^3.0.3
  drift:
    git:
      url: https://github.com/alexmercerind/drift.git
      path: ./drift
      ref: feat/group-concat-order-by
  dynamic_color: ^1.6.9
  ffi: ^2.1.2
  file_picker: ^9.2.2
  fluentui_system_icons: ^1.1.136
  flutter_discord_rpc: 1.0.0
  flutter_local_notifications: ^19.0.0
  flutter_svg: ^1.1.4
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  http: ^1.2.1
  json_annotation: ^4.9.0
  lrc: ^1.0.1
  measure_size: ^4.0.0
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./media_kit
  media_kit_libs_android_audio:
    path: ./libs/android
  media_kit_libs_linux:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_macos_audio:
    path: ./libs/macos
  media_kit_libs_windows_audio:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: ./libs/windows/media_kit_libs_windows_audio
  media_library:
    path: external/media_library
  mesh_gradient: ^1.3.7
  mpris_service:
    git:
      url: https://github.com/alexmercerind/mpris_service.git
      ref: master
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.0.1
  safe_local_storage: ^2.0.1
  share_plus: ^10.1.2
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0
  substring_highlight: ^1.0.33
  syncfusion_flutter_datagrid: 24.2.7
  syncfusion_flutter_sliders: 24.2.7
  synchronized: ^3.0.0+2
  system_media_transport_controls:
    path: external/smtc-win32/bindings/system_media_transport_controls
  tag_reader:
    path: external/tag_reader
  uri_parser: ^3.0.0
  url_launcher: ^6.1.3
  uuid: ^4.3.3
  win32: ^5.2.0
  windows_taskbar:
    git:
      url: https://github.com/alexmercerind/windows_taskbar.git
      ref: b3273d58aab9d71f61b51a84d5c6fb6cf0821529

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev:
    git:
      url: https://github.com/alexmercerind/drift.git
      path: ./drift_dev
      ref: feat/group-concat-order-by
  flutter_lints: ^3.0.1
  freezed: ^2.5.7
  json_serializable: ^6.9.0

dependency_overrides:
  drift:
    git:
      url: https://github.com/alexmercerind/drift.git
      path: ./drift
      ref: feat/group-concat-order-by
  drift_dev:
    git:
      url: https://github.com/alexmercerind/drift.git
      path: ./drift_dev
      ref: feat/group-concat-order-by
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/localizations/
    - assets/localizations/localizations/
    - assets/vectors/
    - assets/visuals/

