name: harmonoid
description: A beautiful app to play all your music.
publish_to: 'none'
version: 0.1.2+5003

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  provider: ^5.0.0
  flutter_acrylic: ^0.0.2
  ffi: ^1.1.2
  libwinmedia:
    path: ./external/libwinmedia.dart
  flutter_media_metadata:
    git:
      url: https://github.com/alexmercerind/flutter_media_metadata.git
      ref: a304b1a51b0f2ed86f0f31df035ba3ef960c7a12
  fluentui_system_icons: ^1.1.136
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  filepicker_windows: ^2.0.0
  bitsdojo_window: ^0.1.1+1
  flutter_local_notifications: ^5.0.0
  file_picker: ^3.0.0
  permission_handler: ^6.1.1
  share_plus: ^2.1.4
  palette_generator: ^0.3.0
  dart_discord_rpc: ^0.0.1
  http: ^0.13.0
  path: ^1.8.0
  url_launcher: ^6.0.3
  implicitly_animated_reorderable_list: ^0.4.0-dev+4

dev_dependencies:
  msix:
    git:
      url: git://github.com/alexmercerind/msix.git
      ref: a2c15a8662dd346b2738ea89538179f532d4f437

flutter:
  uses-material-design: true
  assets:
    - assets/images/about-header.jpg
    - assets/images/collection-album.jpg
    - assets/images/credits-albums.jpg
    - assets/images/credits-tracks.jpg
    - assets/images/credits-artists.jpg
    - assets/images/credits-exception.jpg
    - assets/images/discover-albums.jpg
    - assets/images/discover-tracks.jpg
    - assets/images/discover-artists.jpg
    - assets/images/exception.jpg
    - assets/images/credits-album-art-0.jpg
    - assets/images/credits-album-art-1.jpg
    - assets/images/credits-album-art-2.jpg
    - assets/images/credits-album-art-3.jpg

msix_config:
  msix_version: 0.1.2.0
  display_name: Harmonoid
  identity_name: com.alexmercerind.harmonoid
  file_extension: ogg, ogx, aac, m4a, mp3, wma, wav, aiff, flac, opus
  icons_background_color: transparent
  architecture: x64
  capabilities: broadFileSystemAccess, musicLibrary
  vs_generated_images_folder_path: ./windows/msix/assets
  publisher_display_name: Hitesh Kumar Saini
  publisher: E=saini123hitesh@gmail.com, CN=Hitesh Kumar Saini, OU=com.alexmercerind, O=com.alexmercerind, L=Dehradun, S=Uttarakhand, C=IN
  certificate_path: ./windows/msix/certificate.pfx
  store: false
  