name: harmonoid
description: Plays & manages your music library. Looks beautiful & juicy.
publish_to: "none"
version: 0.3.3+5009

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Plugins maintained by github.com/alexmercerind or first-party to the Harmonoid.

  media_engine:
    path: external/media_engine
  media_library:
    path: external/media_library
  window_plus:
    path: external/window_plus
  system_media_transport_controls:
    path: external/smtc-win32/bindings/system_media_transport_controls.dart
  mpris_service:
    path: external/mpris_service.dart
  harmonoid_visual_assets:
    path: external/harmonoid_visual_assets
  ytm_client:
    path: external/ytm_client.dart
  safe_local_storage:
    path: external/safe_local_storage
  windows_taskbar:
    git:
      url: https://github.com/alexmercerind/windows_taskbar.git
      ref: master
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: 48a15a750d9ee50c521a408c466bd681321a38e2

  # Third-party plugins.

  ffi: ^2.0.1
  win32: ^3.0.0
  just_audio: ^0.9.28
  audio_service: ^0.18.7
  awesome_notifications: ^0.7.0-beta.5
  share_plus: ^2.1.4
  url_launcher: ^6.1.3
  filepicker_windows:
    git:
      url: https://github.com/alexmercerind/filepicker_windows.git
      ref: master
  file_picker: ^5.1.0
  file_selector: ^0.8.2
  permission_handler:
    git:
      url: https://github.com/alexmercerind/flutter-permission-handler.git
      path: permission_handler
      ref: master
  file_selector_linux:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_selector/file_selector_linux
      ref: 4bc2c310e8acf3740ea0c2b326b3ef71280391f8

  # Third-party UI widgets or "pure-dart" packages.

  lrc: ^1.0.1
  http: ^0.13.0
  path: ^1.8.0
  provider: ^6.0.1
  animations: ^2.0.0
  draggable_scrollbar: ^0.1.0
  infinite_scroll_pagination: ^3.1.0
  readmore: ^2.1.0
  fluentui_system_icons: ^1.1.136
  material_floating_search_bar: ^0.3.6
  collection: any
  substring_highlight: ^1.0.33
  extended_image: ^6.0.2
  auto_size_text: ^3.0.0
  uuid: ^3.0.6
  synchronized: ^3.0.0+2
  flutter_speed_dial: ^6.0.0
  flutter_svg: ^1.1.4

  # Third-party forked plugins & packages to meet requirements.

  flutter_platform_alert:
    git:
      url: https://github.com/alexmercerind/flutter_platform_alert.git
      ref: b174a505c6c2c00bad973c2fc285e80d6a85cb7d
  desktop:
    git:
      url: https://github.com/alexmercerind/desktop.git
      path: desktop
      ref: a087d1ed4afeb61edd00e06842fa62c090f30ff5
  hotkey_manager:
    git:
      url: https://github.com/alexmercerind/hotkey_manager.git
      ref: main
  known_extents_list_view_builder:
    git:
      url: https://github.com/alexmercerind/known_extents_list_view_builder.git
  flutter_lyric:
    git:
      url: https://github.com/alexmercerind/flutter_lyric.git
      ref: master

dependency_overrides:
  ffi: 1.1.0
  win32: ^3.0.0
  platform: ^3.1.0
  media_engine:
    path: external/media_engine
  safe_local_storage:
    path: external/safe_local_storage
  permission_handler_platform_interface:
    git:
      url: https://github.com/alexmercerind/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: master
  permission_handler_android:
    git:
      url: https://github.com/alexmercerind/flutter-permission-handler.git
      path: permission_handler_android
      ref: master

dev_dependencies:
  lints: ^2.0.0
  msix:
    git:
      url: https://github.com/alexmercerind/msix.git
      ref: a2c15a8662dd346b2738ea89538179f532d4f437

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/translations/translations/
    - assets/preloaded_visuals/

msix_config:
  msix_version: 0.3.3.0
  display_name: Harmonoid
  identity_name: com.alexmercerind.harmonoid
  file_extension: ogg, oga, ogx, aac, m4a, mp3, wma, wav, flac, opus, aiff, ac3, adt, adts, amr, ec3, m3u, m4r, wpl, zpl
  icons_background_color: transparent
  architecture: x64
  capabilities: broadFileSystemAccess, musicLibrary
  vs_generated_images_folder_path: ./windows/msix/assets
  publisher_display_name: Hitesh Kumar Saini
  publisher: E=github.com/alexmercerind, CN=Hitesh Kumar Saini, OU=com.alexmercerind, O=com.alexmercerind, L=Dehradun, S=Uttarakhand, C=IN
  certificate_path: ./windows/msix/certificate.pfx
  store: false
