name: override_window_destroy
version: 0.0.1

environment:
  sdk: ">=2.14.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: OverrideWindowDestroyPlugin
