name: Github Actions
on: [push, pull_request]

jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: 'recursive'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows

      - run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Harmonoid_InnoSetup.iss"
        shell: cmd
      
      - run: cp -r build/windows/runner/Release harmonoid-windows-exe
      - run: tar.exe -a -c -f harmonoid-windows-exe.zip harmonoid-windows-exe
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ''
          tag_name: 'master'
          files: |
            Output/harmonoid-windows-setup.exe
            harmonoid-windows-exe.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: 'recursive'
      
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: sudo apt-get update
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev libmediainfo-dev dpkg-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux --verbose

      - run: mkdir linux/debian/$(dir linux/debian)/usr/local
      - run: cp -R build/linux/x64/release/bundle linux/debian/$(dir linux/debian)/usr/local/bin -f
      - run: dpkg-deb --build --root-owner-group linux/debian/$(dir linux/debian)
      - run: sudo rm -r linux/debian/$(ls linux/debian | head -1)
      - run: cp linux/debian/$(ls linux/debian | head -1) harmonoid-linux-debian.deb
      - run: cp -r build/linux/x64/release/bundle bundle
      - run: zip -r harmonoid-linux-exe.zip bundle

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ''
          tag_name: 'master'
          files: |
            harmonoid-linux-debian.deb
            harmonoid-linux-exe.zip
          token: ${{ secrets.GITHUB_TOKEN }}
